# Generated by Django 5.0.3 on 2024-03-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
