# Generated by Django 5.0.3 on 2024-03-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producto_dueño_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='dueño',
            new_name='usuario',
        ),
    ]
